summary: XML-based font configuration library
webpage: https://wiki.freedesktop.org/www/Software/fontconfig
version: 2.17.1
bin-url: https://github.com/fpliu1214/uppm-package-repository-macos-15.0-arm64/releases/download/2026.03.30.1/libfontconfig-2.17.1-MacOSX-15.0-arm64.tar.xz
bin-sha: 89ef28539979bea2b78fbb4cd393b71ef9fccde8c7dd46a50ef4633859bd6d34
