summary: Keyboard configuration database for the X Window System
webpage: https://www.freedesktop.org/wiki/Software/XKeyboardConfig/
version: 2.47
bin-url: https://github.com/fpliu1214/uppm-package-repository-macos-15.0-arm64/releases/download/2026.03.30.2/xkeyboard-config-2.47-MacOSX-15.0-arm64.tar.xz
bin-sha: c860aaeeb7a3dfc43b0c1c0f98af1efa6dfae15cdcdf5a74f6dfa1199ee31b19
